title: BC Transit Victoria

author:
  name: Yufan Li

description: A curated collection of BC Transit Victoria vehicle photographs taken by Yufan Li, a transit enthusiast.

theme: minima

minima:
  skin: solarized-light
